---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.volumes.mounts.ssh.config.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  config: |-
{{ .Values.config | indent 4 }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.volumes.mounts.ssh.keys.private.github.name }} 
  namespace: {{ .Release.Namespace }}
data:
  id_rsa_github: |-
{{ .Values.githubKey | indent 4 }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.volumes.mounts.ssh.keys.private.gitlab.name }} 
  namespace: {{ .Release.Namespace }}
data:
  id_rsa_gitlab: |-
{{ .Values.gitlabKey | indent 4 }}
type: Opaque
