---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}
---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#   name: jenkins
#   namespace: jenkins
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - services
#   - endpoints
#   verbs:
#   - get
#   - list
#   - watch
#   - create
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - ""
#   resources:
#   - configmaps
#   verbs:
#   - get
#   - list
#   - watch
#   - update
#   - create
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   verbs:
#   - get
#   - delete
#   - list
# - apiGroups:
#   - ""
#   resources:
#   - events
#   verbs:
#   - create
#   - patch
# - apiGroups:
#   - extensions
#   resources:
#   - ingresses
#   verbs:
#   - list
#   - watch
#   - get
# - apiGroups:
#   - "extensions"
#   resources:
#   - ingresses/status
#   verbs:
#   - update
# - apiGroups:
#   - apps
#   - extensions
#   resources:
#   - deployments
#   verbs:
#   - get
#   - list
#   - watch
#   - create
#   - update
#   - patch
#   - delete
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}
rules: #{{ .Values.clusterRole.rules }}
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["pods"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["", "rbac.authorization.k8s.io"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["secrets"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["configmaps"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
    resources: ["deployments"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["services"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["serviceaccounts"]
    verbs: ["create","delete","get","list","patch","update"]
  - apiGroups: ["", "rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["create","delete","get","list","patch","update"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: {{ .Values.rbac.roleRef.apiGroup }}
  kind: {{ .Values.rbac.roleRef.kind }}
  name: {{ .Values.nameOverride }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-grantor
rules:
- apiGroups: ["", "rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["", "rbac.authorization.k8s.io"]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-rbac
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: role-grantor
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: jenkins
  namespace: jenkins

  