name: "4.EKS Infra TF Apply"

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      workspace:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Select Woorkspace dev/prd"
        # Default value if no value is explicitly provided
        default: ""
        # Input has to be provided for the workflow to run
        required: true

jobs:
  terraform:
    name: "EKS Infra Terraform Apply"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.15.3
      
      # Checkout the #####-credentials repository to the Git runner
      - name: Checkout credentials
        uses: actions/checkout@v2
        with:
          repository: deliveryblueprints/#####-credentials
          path: creds
          ref: main
          ssh-key: ${{ secrets.GH_SSH }}
          ssh-strict: false

      # Decrypt credentials for git runner
      - name: Decrypt AWS Credentials
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "decrypting AWS credentials.."
          mkdir -p $HOME/.aws
          gpg --quiet --batch --yes --decrypt \
              --passphrase="$GPG_KEY" \
              --output $HOME/.aws/credentials \
          creds/aws_credentials.gpg

      # Terraform Apply - dev
      - name: Terraform Apply
        run: cd eks-jenkins/terraform/app-infra && bash terraform.sh ${{ github.event.inputs.workspace }} apply
