---
- name: launch ec2 instance
  ec2:
    key_name: bc-build
    image: "{{image_id}}"
    spot_type: one-time
    spot_price: "0.03"
    wait: yes
    vpc_subnet_id: subnet-085b9bd699a49219d
    instance_type: t3a.large
    group: ['core-management','core-ec2']
    volumes: "{{aws_ami_launch_volumes}}"
    region: eu-west-1
    instance_initiated_shutdown_behavior: terminate
    instance_tags:
      Name: "core-build-{{ami_name}}"
      CreatedBy: Ansible
      Role: build
      Username: "{{ lookup('env','USER') }}"
  register: ec2

- name: wait for ssh
  delegate_to: "{{item.private_ip}}"
  wait_for_connection:
    delay: 60
    timeout: 320
  with_items: "{{ec2.instances}}"

- name: add host to dynamic inventory
  add_host:
    hostname: "{{item['private_ip']}}"
    groupname: "dynamic"
  with_items: "{{ec2.instances}}"
