---
region: us-east-1

##########connect_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33353935666330396333636461633164366462303839623338653534346165326635663037383638
          6139323438316164656630393565643838356662306435640a616636303265383462633335356439
          30363632386136373631366662623062613964333932316337303764353634303766383062393337
          3231306261663938660a393934353630613038313231333230353062356230616563383335396232
          3435

bucket: '##########test2-sql-backup'
file: 'daily-db-backup.sql.gz'

sasyadev_aws_access_key: AKIA4NMNXYOUTZMZUQ4X
sasyadev_aws_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65363433363163363534336563663339663664356361623934326433343434353661623832313362
          6331343931653739626364396239306637306564396439330a316562326266623231393063373263
          34303533323133323237666136316463646139306230656338303234326333306434303332356235
          3463656134353763330a653766633530623339656134373337663262396661643435333163356261
          61366461346335636633363039393834353866623663393663326431626233663336366233643465
          3939363765323730663136343239616266323464316634313330

mariadb_priv_rwx: >-
  ##########.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_cms.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_cms_v2.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_groups.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_lms.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_mailer.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_marketo.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_payments.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_quartz_sched.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  ##########_social.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  cms_v3.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  core.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  license.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  online_applications.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  pricing.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  tmp.*:SELECT,INSERT,UPDATE,EXECUTE,DELETE,CREATE,ALTER,CREATE ROUTINE,CREATE TEMPORARY TABLES,GRANT OPTION,ALTER ROUTINE/
  mysql.proc:SELECT