---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  namespace: jenkins
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/successCodes: "200"
    alb.ingress.kubernetes.io/healthcheck-port: "30069"
  name: nginx
  namespace: jenkins
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30069

---
## Use Jenkins ingress
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: nginx
#   namespace: jenkins
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
#     alb.ingress.kubernetes.io/target-type: instance
#     alb.ingress.kubernetes.io/healthcheck-port: "30069"
#     alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
# spec:
#   rules:
#    - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: nginx
#           servicePort: 80
