---
- hosts: localhost
  become: no
  pre_tasks:
    - name: fetch aws credentials
      sts_assume_role:
        role_arn: "arn:aws:iam::************:role/CoreAccessRole"
        role_session_name: "BuildSession"
      register: assumed_role
    - name: set ami name
      set_fact:
        ami_name: jenkins
    - name: set environment facts
      set_fact:
        environment: &icenv
          AWS_ACCESS_KEY: "{{ assumed_role.sts_creds.access_key }}"
          AWS_SECRET_KEY: "{{ assumed_role.sts_creds.secret_key }}"
          AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
          AWS_DEFAULT_REGION: 'eu-west-2'

- hosts: localhost
  become: no
  environment:
    <<: *bcenv
  vars:
    ami_name_filter: "bc-jenkins-*"
  roles:
    - aws-ami-find
    - aws-ami-launch

- hosts: dynamic
  become: yes
  vars:
    ami: true
  roles:
    - users
    - aws-ami-remove-ec2-key

- hosts: localhost
  become: no
  environment:
    <<: *bcenv
  roles:
    - {
        role: 'aws-ami-create',
        ami_prefix: 'bc',
        aws_regions: ['eu-west-1'],
        ami_wait: "no"
      }
    - {
        role: 'aws-ami-terminate',
        instance_ids: '{{ec2.instance_ids}}'
      }
