---
- name: deploy python script
  copy:
    src: repo-clone-boot/repo-clone-boot.py
    dest: /opt/bc/repo-clone-boot.py
    mode: 0755
    owner: bradley
    group: bradley
  tags:
    - bc-tools

- name: deploy systemd service
  copy:
    src: repo-clone-boot/bc-repo-clone-boot.service
    dest: /usr/lib/systemd/system/bc-repo-clone-boot.service
  notify: reload systemd
  tags:
    - bc-tools
    - systemd

- meta: flush_handlers
  tags:
    - bc-tools
    - systemd

- name: enable bc-repo-clone-boot service
  systemd:
    name: bc-repo-clone-boot
    enabled: yes
  tags:
    - bc-tools
    - systemd
